[package]
name = "nightreign-attack-summon"
version = "0.14.0"
edition = "2024"
repository = "https://github.com/KamiyamaShiki0704/ER_Summon"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
eldenring = { git = "https://github.com/vswarte/fromsoftware-rs.git", rev = "eae96dfec94fd9cf6f9d24813c8d08f72019f243" }
fromsoftware-shared = { git = "https://github.com/vswarte/fromsoftware-rs.git", rev = "eae96dfec94fd9cf6f9d24813c8d08f72019f243" }
toml = "1.1.4"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_System_Kernel",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
]

[lib]
name = "summon"
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
